#! /usr/bin/bash
-e # stop if it fails at any point

pip3 install --user -r /workspaces/aws-bootcamp-cruddur-2023/backend-flask/requirements.txt

#postgres
curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
sudo apt update
sudo apt install -y postgresql-client-13 libpq-dev
#pg:update security group rule 
export CODESPACES_IP=$(curl ifconfig.me)
source "$CODESPACE_VSCODE_FOLDER/backend-flask/rds-update-sg-rule"